spring:
  application:
    name: hhplus-03-server-construction

  # H2 Database 설정
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:test'   # H2 DB 연결 주소 (In-Memory Mode)
    username: sa
    password:

  sql:
    init: # application 실행시 sql 실행
      mode: always
      data-locations: classpath*:db/data.sql
      continue-on-error: true

  # H2 Console 설정
  h2:
    console: # H2 DB를 웹에서 관리할 수 있는 기능
      enabled: true # H2 Console 사용 여부
      path: /h2-console # H2 Console 접속 주소

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: create # DB 초기화 전략 (none, create, create-drop, update, validate)
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true # 쿼리 로그 포맷 (정렬)
        show_sql: true # 쿼리 로그 출력
    defer-datasource-initialization: true


# swagger 설정
springdoc:
  swagger-ui:
    path: /swagger-index
    disable-swagger-default-url: true

